spotlight circle grows in size when gems are collected
monty1289/GameJam pull request #19
Opened 2023-06-14 23:51 UTC by monty1289

The spotlight follows the player and darkens the rest of the scene. also added a script to increase spotlight radius when a gem is collected

2023-06-15 09:12 UTC, CalebStephens requested changes
When i run over the gem nothing is happening?
<img width="235" alt="Screenshot 2023-06-15 at 9 11 54 PM" src="https://github.com/monty1289/GameJam/assets/83677429/cd9e12d0-e16d-407c-b05e-5dedf0ac3534">

2023-06-15 22:09 UTC, monty1289 commented
I had that issue too when using my home computer. will check it out

2023-06-16 01:49 UTC, CalebStephens commented
All that is missing is attaching the light to each gem, easy fix so feel free to merge!

2023-06-16 01:50 UTC, CalebStephens approved these changes

2023-06-16 01:50 UTC, merged